"""move_actor_id_to_user_and_guest

Revision ID: 633961842bad
Revises: e4d07bc5c5a5
Create Date: 2026-05-04 16:43:28.285576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633961842bad'
down_revision: Union[str, Sequence[str], None] = 'e4d07bc5c5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('actors_guest_id_key'), 'actors', type_='unique')
    op.drop_constraint(op.f('actors_user_id_key'), 'actors', type_='unique')
    op.drop_constraint(op.f('actors_guest_id_fkey'), 'actors', type_='foreignkey')
    op.drop_constraint(op.f('actors_user_id_fkey'), 'actors', type_='foreignkey')
    op.drop_column('actors', 'user_id')
    op.drop_column('actors', 'guest_id')
    op.add_column('guests', sa.Column('actor_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'guests', ['actor_id'])
    op.create_foreign_key(None, 'guests', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['actor_id'])
    op.create_foreign_key(None, 'users', 'actors', ['actor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'actor_id')
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_column('guests', 'actor_id')
    op.add_column('actors', sa.Column('guest_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('actors', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('actors_user_id_fkey'), 'actors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('actors_guest_id_fkey'), 'actors', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('actors_user_id_key'), 'actors', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('actors_guest_id_key'), 'actors', ['guest_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
