"""create chat, payment and update other table

Revision ID: 7527602c66f7
Revises: 3665b8af5f97
Create Date: 2026-05-05 09:31:10.734909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7527602c66f7'
down_revision: Union[str, Sequence[str], None] = '3665b8af5f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_actor_id'), 'chat_sessions', ['actor_id'], unique=True)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'ai', name='message_role'), nullable=False, comment='user | ai'),
    sa.Column('message_type', sa.Enum('text', 'service_suggestion', name='message_type'), nullable=False, comment='text = normal bubble | service_suggestion = card with Book Now'),
    sa.Column('message', sa.Text(), nullable=False, comment="message text or ai extra note like 'If you want to know more details...'"),
    sa.Column('service_id', sa.UUID(), nullable=True, comment='which service the AI is suggesting'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=True)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('sub_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gateway', sa.Enum('stripe', name='payment_gateway'), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(), nullable=True, comment='Stripe payment intent or charge ID'),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_transaction_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=True)
    op.add_column('booking_requests', sa.Column('location', sa.String(), nullable=True))
    op.add_column('booking_requests', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.add_column('booking_requests', sa.Column('scheduled_time', sa.Time(), nullable=True))
    op.add_column('services', sa.Column('property_size', sa.String(), nullable=False, comment='e.g. 1 bedroom | 2 bedrooms | 3 bedrooms'))
    op.alter_column('services', 'service_type',
               existing_type=postgresql.ENUM('plumbing', 'electrical', 'cleaning', 'repair', 'other', name='service_type'),
               type_=sa.String(),
               comment='e.g. Residential Cleaning | Deep Clean | Office Cleaning',
               existing_nullable=False)
    op.alter_column('services', 'distance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='max distance in km e.g. 2 | 5 | 8',
               existing_nullable=False)
    op.drop_column('services', 'property_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('property_type', postgresql.ENUM('residential', 'commercial', 'industrial', name='property_type'), autoincrement=False, nullable=False))
    op.alter_column('services', 'distance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='max distance in km e.g. 2 | 5 | 8',
               existing_nullable=False)
    op.alter_column('services', 'service_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('plumbing', 'electrical', 'cleaning', 'repair', 'other', name='service_type'),
               comment=None,
               existing_comment='e.g. Residential Cleaning | Deep Clean | Office Cleaning',
               existing_nullable=False)
    op.drop_column('services', 'property_size')
    op.drop_column('booking_requests', 'scheduled_time')
    op.drop_column('booking_requests', 'scheduled_date')
    op.drop_column('booking_requests', 'location')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_actor_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
